/**
 * Planner agent — deterministic by default, LLM-backed when configured.
 *
 * Mode is controlled by the PLANNER_MODE environment variable:
 *   deterministic  — no LLM, same output every time (default)
 *   local-llm      — proposals generated by OllamaProvider
 *   future-cloud   — stub, throws until implemented
 *
 * In all modes the result is the same shape: one proposal file per unique
 * subject pair written to `output/proposals/<slug>.json`. The deterministic
 * path is guaranteed unchanged — no behavior difference unless PLANNER_MODE
 * is explicitly overridden.
 */

const path = require("path");
const { CATALOG } = require("./catalog.ts");
const { writeJSON, ensureDir, slugify } = require("./fsutil.ts");

type PlannerMode = "deterministic" | "local-llm" | "future-cloud";

type CategorySubjects = { category: string; subjects: string[] };

type Pair = { subjectA: string; subjectB: string };

type Proposal = {
  subjectA: string;
  subjectB: string;
  category: string;
  title: string;
  rationale: string;
};

type PlannerResult = {
  slug: string;
  proposalPath: string;
  subjectA: string;
  subjectB: string;
};

const PLANNER_MODE: PlannerMode =
  (process.env.PLANNER_MODE as PlannerMode) ?? "deterministic";

function slugFor(pair: Pair): string {
  return `${slugify(pair.subjectA)}-vs-${slugify(pair.subjectB)}`;
}

/**
 * Deterministically finds the catalog entry for a given category name
 * (case-insensitive). Always returns the same result for the same input —
 * no randomness, no AI.
 */
function selectCategory(category: string): CategorySubjects {
  const normalized = category.trim().toLowerCase();
  const match = (CATALOG as CategorySubjects[]).find(
    (entry) => entry.category.toLowerCase() === normalized
  );
  if (!match) {
    const known = (CATALOG as CategorySubjects[]).map((e) => e.category).join(", ");
    throw new Error(`No catalog entry for category "${category}". Known categories: ${known}`);
  }
  return match;
}

/**
 * Every unique unordered pair from a list of subjects, in a fixed
 * (catalog-order) sequence — no duplicates, no (B, A) mirror of an
 * already-listed (A, B) pair.
 */
function buildPairs(subjects: string[]): Pair[] {
  const pairs: Pair[] = [];
  for (let i = 0; i < subjects.length; i++) {
    for (let j = i + 1; j < subjects.length; j++) {
      pairs.push({ subjectA: subjects[i], subjectB: subjects[j] });
    }
  }
  return pairs;
}

function buildProposal(pair: Pair, category: string): Proposal {
  return {
    subjectA: pair.subjectA,
    subjectB: pair.subjectB,
    category,
    title: `${pair.subjectA} vs ${pair.subjectB}`,
    rationale: `Deterministically selected from the static ${category} catalog — no AI, no randomness.`,
  };
}

function writeProposal(pair: Pair, category: string, proposalsDir: string): PlannerResult {
  const slug = slugFor(pair);
  const proposal = buildProposal(pair, category);
  const proposalPath = path.join(proposalsDir, `${slug}.json`);
  writeJSON(proposalPath, proposal);
  return { slug, proposalPath, subjectA: pair.subjectA, subjectB: pair.subjectB };
}

// ---------------------------------------------------------------------------
// Deterministic path (unchanged behavior)
// ---------------------------------------------------------------------------

function runPlannerBatchDeterministic(
  entry: CategorySubjects,
  proposalsDir: string
): PlannerResult[] {
  const pairs = buildPairs(entry.subjects);
  ensureDir(proposalsDir);
  return pairs.map((pair) => writeProposal(pair, entry.category, proposalsDir));
}

// ---------------------------------------------------------------------------
// LLM path
// ---------------------------------------------------------------------------

async function runPlannerBatchLLM(
  entry: CategorySubjects,
  proposalsDir: string
): Promise<PlannerResult[]> {
  const { createProvider } = require("./llm/provider.ts");
  const provider = createProvider(PLANNER_MODE);

  console.log(`  [Planner] Mode: ${PLANNER_MODE} — using ${provider.name}`);

  const llmProposals = await provider.generateProposals(entry.category, entry.subjects);

  const validSubjects = new Set(entry.subjects);
  const seen = new Set<string>();
  const results: PlannerResult[] = [];

  ensureDir(proposalsDir);

  for (const item of llmProposals) {
    if (!validSubjects.has(item.subjectA) || !validSubjects.has(item.subjectB)) {
      console.warn(
        `  [Planner] Skipping pair not in catalog: "${item.subjectA}" vs "${item.subjectB}"`
      );
      continue;
    }
    if (item.subjectA === item.subjectB) continue;

    const key = [item.subjectA, item.subjectB].sort().join("||");
    if (seen.has(key)) continue;
    seen.add(key);

    const pair: Pair = { subjectA: item.subjectA, subjectB: item.subjectB };
    const slug = slugFor(pair);
    const proposal: Proposal = {
      subjectA: pair.subjectA,
      subjectB: pair.subjectB,
      category: entry.category,
      title: `${pair.subjectA} vs ${pair.subjectB}`,
      rationale: `Generated by ${PLANNER_MODE} mode via ${provider.name}.`,
    };
    const proposalPath = path.join(proposalsDir, `${slug}.json`);
    writeJSON(proposalPath, proposal);
    results.push({ slug, proposalPath, subjectA: pair.subjectA, subjectB: pair.subjectB });
  }

  if (results.length === 0) {
    throw new Error(
      `LLM provider returned no valid proposals for category "${entry.category}". ` +
        "All pairs were either invalid, duplicates, or contained unknown subjects."
    );
  }

  return results;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Runs the Planner for a given category. In deterministic mode returns
 * synchronously (wrapped in a resolved Promise for a uniform interface).
 * In local-llm mode awaits the provider. Always returns the full proposal
 * batch so the pipeline runner knows every battle to process next.
 */
async function runPlannerBatch(
  category: string,
  proposalsDir: string
): Promise<PlannerResult[]> {
  const entry = selectCategory(category);

  if (PLANNER_MODE === "deterministic") {
    return runPlannerBatchDeterministic(entry, proposalsDir);
  }

  return runPlannerBatchLLM(entry, proposalsDir);
}

module.exports = {
  runPlannerBatch,
  selectCategory,
  buildPairs,
  buildProposal,
  slugFor,
  slugify,
};
