/**
 * Publisher agent — first real (non-stub) implementation.
 *
 * Deterministic only: no AI, no API calls, no upload. Reads an already
 * Reviewer-approved Battle Package and repackages its existing content
 * into per-platform publication folders under `output/published/<slug>/`.
 * It never invents new copy — only reformats what the Battle Designer
 * already wrote. The Battle Package remains the single source of truth;
 * this agent only derives from it, never the other way around.
 */

const path = require("path");
const { readText, writeText, ensureDir, tryReadJSON } = require("./fsutil.ts");

/**
 * Generates output/published/<slug>/ from an existing, Reviewer-approved
 * Battle Package at battleDir. Returns the published directory path.
 *
 * Defensively re-checks review.json itself (not just trusting the caller)
 * so this agent refuses to run on a rejected/unreviewed package even if
 * invoked independently of the pipeline (see agents/publisher/INPUT_SPEC.md).
 */
function runPublisher(slug: string, battleDir: string, publishedDir: string): string {
  const review = tryReadJSON(path.join(battleDir, "review.json")) as
    | { approved?: boolean }
    | null;
  if (!review || review.approved !== true) {
    throw new Error(
      `Publisher refused to run: ${slug} has no approved review.json (run the Reviewer first)`
    );
  }

  const battle = JSON.parse(readText(path.join(battleDir, "battle.json")));
  const caption = readText(path.join(battleDir, "caption.txt")).trim();
  const hashtags = readText(path.join(battleDir, "hashtags.txt")).trim();
  const script = readText(path.join(battleDir, "script.txt")).trim();
  const imagePrompt = readText(path.join(battleDir, "image_prompt.txt")).trim();
  const videoPrompt = readText(path.join(battleDir, "video_prompt.txt")).trim();

  const title = `${battle.subjectA.name} vs ${battle.subjectB.name}`;
  const outDir = path.join(publishedDir, slug);
  const tiktokDir = path.join(outDir, "tiktok");
  const instagramDir = path.join(outDir, "instagram");
  const youtubeDir = path.join(outDir, "youtube");

  ensureDir(tiktokDir);
  ensureDir(instagramDir);
  ensureDir(youtubeDir);

  writeText(
    path.join(outDir, "README.md"),
    [
      `# Published package — ${title}`,
      "",
      "Generated by the Publisher agent from an existing, Reviewer-approved",
      `Battle Package (\`output/battles/${slug}/\`). No API calls, no upload —`,
      "package generation only. Content is reformatted from the Battle Package,",
      "never invented here.",
      "",
      "## Contents",
      "",
      "- `tiktok/` — caption, hashtags, script, image/video prompts",
      "- `instagram/` — caption, hashtags",
      "- `youtube/` — title, description, hashtags",
    ].join("\n")
  );

  // TikTok
  writeText(path.join(tiktokDir, "caption.txt"), caption);
  writeText(path.join(tiktokDir, "hashtags.txt"), hashtags);
  writeText(path.join(tiktokDir, "script.txt"), script);
  writeText(path.join(tiktokDir, "video_prompt.txt"), videoPrompt);
  writeText(path.join(tiktokDir, "image_prompt.txt"), imagePrompt);

  // Instagram (same caption/hashtags — Instagram has no separate script/prompt fields here)
  writeText(path.join(instagramDir, "caption.txt"), caption);
  writeText(path.join(instagramDir, "hashtags.txt"), hashtags);

  // YouTube
  writeText(path.join(youtubeDir, "title.txt"), title);
  writeText(
    path.join(youtubeDir, "description.txt"),
    `${caption}\n\nCommunity signal, not a scientific poll.`
  );
  writeText(path.join(youtubeDir, "hashtags.txt"), hashtags);

  return outDir;
}

module.exports = { runPublisher };
